---
title: Jörn Threlfall
timezone: UTC
collections:
  archive:
    title: Archive
    output: true
  commercial:
    title: Commercial
    output: true
  film:
    title: Film
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
url: https://www.jornthrelfall.com
description: Jörn Threlfall is a Bafta-nomitated director, represented by Outsider.
permalink: pretty
exclude:
- bower.json
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
- ".jekyll-cache"
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
markdown: kramdown
kramdown:
  auto_ids: false
  input: GFM
  hard_wrap: false
highlighter: rouge
colophon: https://www.garethjohnsdesign.com
company: Jörn Threlfall
email: info@jornthrelfall.com
google-site-verification: 81MJuIf4Ycj2Ohpq-HikxXDNSpqyKR6FB-SW99W8Ugw
analytics: UA-61972147-1
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%d %B %Y"
future: true
social:
  twitter: https://twitter.com/jornthrelfall
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
pagination:
  enabled: true
  per_page: 100
imgix:
  source: jorn-threlfall.imgix.net
